# debug
debug = True
SWEEPTOPIC = 'iot-2/evt/sweep/fmt/json'
SYSCALTOPIC = 'iot-2/evt/syscal/fmt/json'
CONDCALTOPIC = 'iot-2/evt/condcal/fmt/json'
CONDRDTOPIC = 'iot-2/evt/condrd/fmt/json'
INITTOPIC = 'iot-2/evt/init/fmt/json'
WFCHGREQ = 'iot-2/evt/wifichg/fmt/json'
BMXCREDCHGREQ = 'iot-2/evt/bmxchg/fmt/json'
RUNTOPIC = 'iot-2/evt/running/fmt/json'
GETCONFIG = 'iot-2/evt/getcfg/fmt/json'
PINGTOPIC = 'iot-2/evt/ping/fmt/json'
BATLTOPIC = 'iot-2/evt/battrd/fmt/json'
DEEPSLP = 'iot-2/evt/deepslp/fmt/json'
ANINIT = 'iot-2/evt/aninit/fmt/json'
SUBSCRIBE = 'iot-2/cmd/+/fmt/json'
